export const FIELD_NAMES = {
  fullName: "Full Name",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  avatar: "Profile Picture",
  bio: "Bio",
  title: "Recipe Title",
  description: "Description",
  instructions: "Instructions",
  ingredients: "Ingredients",
  prepTime: "Prep Time (minutes)",
  cookTime: "Cook Time (minutes)",
  servings: "Servings",
  difficulty: "Difficulty",
  cuisine: "Cuisine",
  tags: "Tags",
  imageUrl: "Recipe Image",
  videoUrl: "Video URL",
  nutritionInfo: "Nutrition Information",
  isPublic: "Make Public",
  name: "Name",
  comment: "Comment",
  rating: "Rating",
  category: "Category",
  quantity: "Quantity",
  unit: "Unit",
  expiryDate: "Expiry Date",
  startDate: "Start Date",
  endDate: "End Date",
  dayOfWeek: "Day of Week",
  mealType: "Meal Type",
} as const;

export const FIELD_TYPES = {
  fullName: "text",
  email: "email",
  password: "password",
  confirmPassword: "password",
  avatar: "file",
  bio: "textarea",
  title: "text",
  description: "textarea",
  prepTime: "number",
  cookTime: "number",
  servings: "number",
  imageUrl: "url",
  videoUrl: "url",
  name: "text",
  comment: "textarea",
  rating: "number",
  category: "text",
  quantity: "number",
  unit: "text",
  expiryDate: "date",
  startDate: "date",
  endDate: "date",
  dayOfWeek: "number",
} as const;

export const DIFFICULTY_OPTIONS = [
  { value: "EASY", label: "Easy", description: "Quick and simple recipes" },
  { value: "MEDIUM", label: "Medium", description: "Moderate skill required" },
  { value: "HARD", label: "Hard", description: "Advanced techniques needed" },
  { value: "EXPERT", label: "Expert", description: "Professional level cooking" },
] as const;

export const CUISINE_OPTIONS = [
  { value: "AMERICAN", label: "American" },
  { value: "ITALIAN", label: "Italian" },
  { value: "MEXICAN", label: "Mexican" },
  { value: "ASIAN", label: "Asian" },
  { value: "INDIAN", label: "Indian" },
  { value: "FRENCH", label: "French" },
  { value: "MEDITERRANEAN", label: "Mediterranean" },
  { value: "OTHER", label: "Other" },
] as const;

export const MEAL_TYPES = [
  { value: "breakfast", label: "Breakfast" },
  { value: "lunch", label: "Lunch" },
  { value: "dinner", label: "Dinner" },
  { value: "snack", label: "Snack" },
] as const;

export const DAYS_OF_WEEK = [
  { value: 0, label: "Sunday" },
  { value: 1, label: "Monday" },
  { value: 2, label: "Tuesday" },
  { value: 3, label: "Wednesday" },
  { value: 4, label: "Thursday" },
  { value: 5, label: "Friday" },
  { value: 6, label: "Saturday" },
] as const;

export const PANTRY_CATEGORIES = [
  "Produce",
  "Dairy",
  "Meat & Seafood",
  "Pantry Staples",
  "Spices & Herbs",
  "Baking",
  "Beverages",
  "Frozen",
  "Canned Goods",
  "Other",
] as const;

export const COMMON_UNITS = [
  "cups",
  "tablespoons",
  "teaspoons",
  "pounds",
  "ounces",
  "grams",
  "kilograms",
  "liters",
  "milliliters",
  "pieces",
  "cloves",
  "slices",
  "pinches",
  "dashes",
] as const;
